import { jsPDF } from "jspdf";
import { ColoringPage } from "../types";

export const generatePDF = (theme: string, pages: ColoringPage[]) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- COVER PAGE ---
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Title Border
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(1);
  doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(40);
  doc.text("Coloring Book", pageWidth / 2, 90, { align: "center" });

  doc.setFontSize(24);
  doc.setFont("helvetica", "normal");
  doc.text(`Theme: ${theme}`, pageWidth / 2, 120, { align: "center" });

  doc.setFontSize(12);
  doc.text("Generated by DreamColor AI", pageWidth / 2, pageHeight - 30, { align: "center" });

  // --- IMAGE PAGES ---
  pages.forEach((page, index) => {
    if (page.status === 'completed' && page.imageUrl) {
      doc.addPage();
      
      // Add Image
      // A4 is 210 x 297 mm
      // Margins 10mm
      const margin = 10;
      const imgWidth = pageWidth - (margin * 2);
      const imgHeight = pageHeight - (margin * 2) - 20; // Leave space for caption
      
      doc.addImage(page.imageUrl, "JPEG", margin, margin, imgWidth, imgHeight);
      
      // Caption (Prompt) - Truncated if too long
      doc.setFontSize(10);
      const safePrompt = doc.splitTextToSize(`Page ${index + 1}: ${page.prompt}`, imgWidth);
      // Only take first 2 lines to avoid overflow
      const lines = safePrompt.length > 2 ? safePrompt.slice(0, 2) : safePrompt;
      
      doc.text(lines, pageWidth / 2, pageHeight - 15, { align: "center" });
    }
  });

  // Sanitize filename
  const filename = theme.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`coloring_book_${filename}.pdf`);
};